project:
  type: website
  output-dir: docs  # GitHub Pages reads from /docs

website:
  title: "Marvin Penguin"
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Talks
    right:
      - href: cv.pdf
        text: CV

  # Footer
  page-footer:
    center: "© 2025 Marvin Penguin"

format:
  html:
    theme: litera        # try: cosmo, flatly, minty, quartz, sandstone, yeti
    css: styles.css
    toc: false
